---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mcsps-webex-receiver
  name: mcsps-webex-receiver
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mcsps-webex-receiver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mcsps-webex-receiver
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - image: akshay123007/infrastructure-alerts:v1
        imagePullPolicy: IfNotPresent
        name: webex
        ports:
          - containerPort: 9091
        env:
        # possible proxy configuration for Webex-API
        # - name: https_proxy
        #   value: "http://10.105.124.65:8084"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: WEBHOOKPORT
          value: "9091"
        - name: WEBEX_TOKEN
          valueFrom:
            secretKeyRef:
              name: mcsps-webex-receiver
              key: WEBEX_TOKEN
        - name: WEBEX_ROOM
          valueFrom:
            secretKeyRef:
              name: mcsps-webex-receiver
              key: WEBEX_ROOM
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: tmp
        emptyDir:
          medium: Memory
